name: buttonroyale
favicon: null
layout_spectrum: 0.46931
typography_spectrum: 0.68712
title: Button Royale
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#847b72'
    - '#a99f96'
    - '#222121'
  brandStrength: 0.5
  lightness: 0.20113150193355978
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
