name: buttonroyale
favicon: null
layout_spectrum: 0.50481
typography_spectrum: 0.14019
title: Button Royale
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#847b72'
    - '#a99f96'
    - '#222121'
  brandStrength: 0.6875
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
