name: buttonroyale
favicon: null
layout_spectrum: 0.906985177192837
typography_spectrum: 0.5257736505009234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6863774503581226
  lightness: 0.20113150193355978
  saturation: 0.3685815909411758
  rhythmicContrast: 0.0462382105179131
purpose: []
